use_frameworks!
platform :ios, 8.0

target 'APNGImageSerialization_Example' do
  pod 'APNGImageSerialization', :path => '../'

  target 'APNGImageSerialization_Tests' do
    inherit! :search_paths
    
  end
end

target 'APNGwatchOSDemo Extension' do
    platform :watchos, '3.0'
    pod 'APNGImageSerialization', :path => '../'
end
